Repository eunji-company/taskflow-spring, pull requests merged in 2025-09, with the labels that each got.

#8 feat: 공통 응답 규격 구현
  src/main/java/indiv/abko/taskflow/global/dto/CommonResponse.java
Labels: ✨ feat

#41 feat: 팀 생성 기능 구현
  src/main/java/indiv/abko/taskflow/domain/team/controller/TeamController.java
  src/main/java/indiv/abko/taskflow/domain/team/dto/request/TeamCreateRequest.java
  src/main/java/indiv/abko/taskflow/domain/team/dto/response/TeamCreateResponse.java
  src/main/java/indiv/abko/taskflow/domain/team/entity/Team.java
  src/main/java/indiv/abko/taskflow/domain/team/exception/TeamErrorCode.java
  src/main/java/indiv/abko/taskflow/domain/team/repository/TeamRepository.java
  src/main/java/indiv/abko/taskflow/domain/team/service/CreateTeamUseCase.java
  src/main/java/indiv/abko/taskflow/domain/team/service/TeamService.java
  src/test/java/indiv/abko/taskflow/team/service/CreateTeamUseCaseTest.java
Labels: ✨ feat

#42 feat: 인증/인가 관련 전역 설정
  build.gradle
  src/main/java/indiv/abko/taskflow/domain/auth/exception/AuthErrorCode.java
  src/main/java/indiv/abko/taskflow/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/indiv/abko/taskflow/global/config/SecurityConfig.java
  src/main/java/indiv/abko/taskflow/global/exception/GlobalExceptionHandler.java
  src/main/java/indiv/abko/taskflow/global/jwt/JwtAuthenticationConverter.java
  src/main/java/indiv/abko/taskflow/global/jwt/JwtAuthenticationToken.java
  src/main/java/indiv/abko/taskflow/global/jwt/JwtUtil.java
  src/test/java/indiv/abko/taskflow/global/auth/CustomAuthenticationEntryPointTest.java
  src/test/java/indiv/abko/taskflow/global/jwt/JwtAuthenticationConverterUnitTest.java
  src/test/java/indiv/abko/taskflow/global/jwt/JwtAuthenticationTokenUnitTest.java
  src/test/java/indiv/abko/taskflow/global/jwt/JwtUtilUnitTest.java
  src/test/java/indiv/abko/taskflow/global/jwt/TestJwtUtil.java
Labels: ✨ feat

#48 feat: Member api - getByIdOrThrow 메서드 작성
  src/main/java/indiv/abko/taskflow/domain/user/service/MemberService.java
  src/main/java/indiv/abko/taskflow/domain/user/service/MemberServiceApi.java
  src/test/java/indiv/abko/taskflow/domain/user/controller/MemberControllerTest.java
  src/test/java/indiv/abko/taskflow/domain/user/repository/MemberRepositoryTest.java
Labels: ✨ feat

#52 feat: 나의 댓글을 삭제하는 기능 구현
  src/main/java/indiv/abko/taskflow/domain/comment/controller/CommentController.java
  src/main/java/indiv/abko/taskflow/domain/comment/dto/command/DeleteMyCommentCommand.java
  src/main/java/indiv/abko/taskflow/domain/comment/exception/CommentErrorCode.java
  src/main/java/indiv/abko/taskflow/domain/comment/mapper/CommentMapper.java
  src/main/java/indiv/abko/taskflow/domain/comment/repository/CommentRepository.java
  src/main/java/indiv/abko/taskflow/domain/comment/service/DeleteMyCommentUseCase.java
  src/test/java/indiv/abko/taskflow/domain/comment/controller/CommentControllerTest.java
  src/test/java/indiv/abko/taskflow/domain/comment/mapper/CommentMapperTest.java
  src/test/java/indiv/abko/taskflow/domain/comment/service/DeleteMyCommentUseCaseTest.java
Labels: ✨ feat

#57 fix: `댓글이_존재하지_않으면_실패한다` 메서드의 버그 수정
  src/test/java/indiv/abko/taskflow/domain/comment/service/DeleteMyCommentUseCaseTest.java
Labels: 🐞 bug

#64 chore: WebMvcConfig에 CORS 관련 설정 추가
  src/main/java/indiv/abko/taskflow/global/config/WebMvcConfig.java
Labels: 🧹 chore

#72 feat: 대댓글 작성 기능 구현
  src/main/java/indiv/abko/taskflow/domain/comment/controller/CommentController.java
  src/main/java/indiv/abko/taskflow/domain/comment/dto/command/WriteCommentToCommentCommand.java
  src/main/java/indiv/abko/taskflow/domain/comment/dto/response/WriteCommentToCommentResponse.java
  src/main/java/indiv/abko/taskflow/domain/comment/entity/Comment.java
  src/main/java/indiv/abko/taskflow/domain/comment/mapper/CommentMapper.java
  src/main/java/indiv/abko/taskflow/domain/comment/service/WriteCommentToCommentUseCase.java
  src/test/java/indiv/abko/taskflow/domain/comment/controller/CommentControllerTest.java
  src/test/java/indiv/abko/taskflow/domain/comment/service/WriteCommentToCommentUseCaseTest.java
Labels: ✨ feat

#74 feat: spring security CORS 설정 추가
  src/main/java/indiv/abko/taskflow/global/config/SecurityConfig.java
  src/main/java/indiv/abko/taskflow/global/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: ✨ feat

#78 fix: 불필요한 코드 제거 및 정리
  src/main/java/indiv/abko/taskflow/domain/task/controller/TaskController.java
  src/main/java/indiv/abko/taskflow/domain/task/dto/reqeust/CreateTaskRequest.java
Labels: 🐞 bug

#80 feat: 로그인 구현
  src/main/java/indiv/abko/taskflow/domain/auth/controller/AuthController.java
  src/main/java/indiv/abko/taskflow/domain/auth/dto/command/LoginCommand.java
  src/main/java/indiv/abko/taskflow/domain/auth/dto/request/LoginRequest.java
  src/main/java/indiv/abko/taskflow/domain/auth/dto/response/LoginResponse.java
  src/main/java/indiv/abko/taskflow/domain/auth/exception/AuthErrorCode.java
  src/main/java/indiv/abko/taskflow/domain/auth/mapper/AuthMapper.java
  src/main/java/indiv/abko/taskflow/domain/auth/service/LoginUseCase.java
  src/main/java/indiv/abko/taskflow/domain/user/service/MemberServiceApi.java
  src/test/java/indiv/abko/taskflow/domain/auth/controller/AuthControllerTest.java
  src/test/java/indiv/abko/taskflow/domain/auth/service/LoginUseCaseTest.java
Labels: ✨ feat

#82 fix: ViewAvailableMembers 불필요한 에러 처리 삭제
  src/main/java/indiv/abko/taskflow/domain/user/controller/MemberController.java
  src/main/java/indiv/abko/taskflow/domain/user/service/ViewAvailableMembersInfoUseCase.java
  src/test/java/indiv/abko/taskflow/domain/user/service/ViewAvailableMembersInfoUseCaseTest.java
Labels: 🔧 fix

#85 fix: ReadTeamUseCase에서 팀 + 멤버 조회 로직 수정
  src/main/java/indiv/abko/taskflow/domain/team/repository/TeamRepository.java
  src/main/java/indiv/abko/taskflow/domain/team/service/ReadTeamUseCase.java
  src/test/java/indiv/abko/taskflow/domain/team/service/ReadTeamUseCaseTest.java
Labels: 🐞 bug

#88 fix: Member Response의 LocalDateTime을 Instant로 변경
  src/main/java/indiv/abko/taskflow/domain/user/dto/MemberInfoResponse.java
  src/main/java/indiv/abko/taskflow/domain/user/service/ViewAvailableMembersInfoUseCase.java
  src/main/java/indiv/abko/taskflow/domain/user/service/ViewMemberInfoUseCase.java
  src/test/java/indiv/abko/taskflow/domain/user/controller/MemberControllerTest.java
  src/test/java/indiv/abko/taskflow/domain/user/service/ViewAvailableMembersInfoUseCaseTest.java
  src/test/java/indiv/abko/taskflow/domain/user/service/ViewMemberInfoUseCaseTest.java
Labels: 🔧 fix

#92 feat: 팀 멤버 목록 조회 기능 구현
  src/main/java/indiv/abko/taskflow/domain/team/controller/TeamController.java
  src/main/java/indiv/abko/taskflow/domain/team/dto/response/ReadTeamMembersResponse.java
  src/main/java/indiv/abko/taskflow/domain/team/service/ReadTeamMembersUseCase.java
  src/test/java/indiv/abko/taskflow/domain/team/service/ReadTeamMembersUseCaseTest.java
Labels: ✨ feat

#96 feat: Spring security 인가 설정
  .gitignore
  src/main/java/indiv/abko/taskflow/domain/auth/annotation/IsAdmin.java
  src/main/java/indiv/abko/taskflow/domain/auth/exception/AuthErrorCode.java
  src/main/java/indiv/abko/taskflow/domain/team/controller/TeamController.java
  src/main/java/indiv/abko/taskflow/global/config/SecurityConfig.java
  src/main/java/indiv/abko/taskflow/global/exception/GlobalExceptionHandler.java
  src/test/java/indiv/abko/taskflow/integration/TeamApiIntegrationTest.java
  src/test/resources/application-test.yml
Labels: ✨ feat

#98 feat: Task 상세 조회 구현
  src/main/java/indiv/abko/taskflow/domain/task/controller/TaskController.java
  src/main/java/indiv/abko/taskflow/domain/task/dto/response/FindTaskResponse.java
  src/main/java/indiv/abko/taskflow/domain/task/service/FindTaskUseCase.java
Labels: ✨ feat

#115 fix: 전반적인 task 기능 수정
  src/main/java/indiv/abko/taskflow/domain/task/controller/TaskController.java
  src/main/java/indiv/abko/taskflow/domain/task/entity/Task.java
  src/main/java/indiv/abko/taskflow/domain/task/repository/TaskRepository.java
  src/main/java/indiv/abko/taskflow/domain/task/service/CreateTaskUseCase.java
  src/main/java/indiv/abko/taskflow/domain/task/service/DeleteTaskUseCase.java
  src/main/java/indiv/abko/taskflow/domain/task/service/FindAllTasksUseCase.java
  src/main/java/indiv/abko/taskflow/domain/task/service/UpdateStatusUseCase.java
  src/main/java/indiv/abko/taskflow/domain/task/service/UpdateTaskUseCase.java
  src/test/java/indiv/abko/taskflow/domain/task/service/CreateTaskUseCaseTest.java
  src/test/java/indiv/abko/taskflow/domain/task/service/FindAllTasksUseCaseTest.java
  src/test/java/indiv/abko/taskflow/domain/task/service/UpdateTaskUseCaseTest.java
Labels: 🐞 bug, 🔧 fix
